services:
  app:
    build: .
    container_name: onfly_app
    ports:
      - "8000:8000" 
    volumes:
      - ./src:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=onfly
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    networks:
      - app-network

  mysql:
    image: mysql/mysql-server:8.0.23
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    platform: linux/amd64
    container_name: mysql_onfly
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
