CREATE DATABASE IF NOT EXISTS onfly;
CREATE DATABASE IF NOT EXISTS onfly_test;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'secret';

GRANT ALL PRIVILEGES ON onfly.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON onfly_test.* TO 'admin'@'%';

FLUSH PRIVILEGES;
